apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: julian-juho-ooo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-pvc
  namespace: julian-juho-ooo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
